using Speakr.Data;
using Speakr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Speakr.Controllers
{
    public class TalksController : ApiController
    {
        public IEnumerable<Talk> GetAll()
        {
            using (var session = RavenInstance.Db.OpenSession())
            {
                var user = default(User);
                if (User.Identity.IsAuthenticated)
                {
                    user = session.Query<User>().FirstOrDefault(u => u.Email == User.Identity.Name);
                }

                var talks = session
                    .Query<Talk>()
                    .OrderByDescending(d => d.TotalRanking)
                    .ToArray();

                // Set the "YouVoted" value if the user is signed in.
                if (user != null)
                {                    
                    foreach (var rating in user.Ratings)
	                {
                        var talk = talks.FirstOrDefault(t => t.Id == rating.TalkId);
                        if (talk != null)
                        {
                            talk.YouVoted = rating.Stars;
                        }
	                }                    
                }

                return talks;
            }
        }
        
        public Talk Rate(TalkRating talkRating)
        {
            if (!User.Identity.IsAuthenticated)
            {
                throw new InvalidOperationException("You must be logged in.");
            }

            using (var session = RavenInstance.Db.OpenSession())
            {
                var user = session.Query<User>().First(u => u.Email == User.Identity.Name);
                var existingRating = user.Ratings.FirstOrDefault(r => r.TalkId == talkRating.TalkId);
                var existingStarCount = 0;
                if (existingRating != null)
                {
                    existingStarCount = existingRating.Stars;
                    existingRating.Stars = talkRating.Stars;
                }
                else
                {
                    user.Ratings.Add(talkRating);
                }

                // Update the talk.
                var talk = session.Load<Talk>(talkRating.TalkId);
                if (existingRating == null)
                {
                    talk.VoteCount = talk.VoteCount + 1;
                }
                else
                {
                    talk.TotalRanking -= StarsToTotalRanking(existingStarCount);
                }

                talk.TotalRanking += StarsToTotalRanking(talkRating.Stars);                
                session.SaveChanges();

                return talk;
            }
        }

        private int StarsToTotalRanking(int stars)
        {
            switch (stars)
            {
                case 1: return -2; 
                case 2: return -1;
                case 3: return 1;
                case 4: return 2;
                case 5: return 3;
                default: return 0;
            }
        }

        //public string GetFoo(int count)
        //{
        //    CreateTalks();
        //    return "ok!";
        //}

        private void CreateTalks()
        {
            var allTalks = new[] 
            {
                new Talk { Author = "Kristina Durivage", Title = "An Overview of D3.js Charting Libraries",  DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KristinaDurivage.jpg", Stars = 0, TotalRanking = 0, Description = "D3.js is a powerful framework for data visualization. However, when all you need is a nice looking javascript bar chart, the idea of learning enough D3 get the job done can be a bit overwhelming. When you stumble upon your first charting library built on D3.js, you might feel relieved, but when you stumble upon your fifth, you are probably back to being overwhelmed. This talk will go through some of these alternatives and help you understand what the differences are between them so you can decide what makes the most sense for your needs.", AuthorInfo = "Kristina Durivage (@gelicia) is a software engineer and data visualization hobbyist living in Minneapolis.", AuthorTwitter = "@gelicia", Room = "3-180", VoteCount = 0 },
                new Talk { Author = "Nick Melnick", Title = "Ambition: A New MVC Web Framework for Vala", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/NickMelnick.jpg", Stars = 0, TotalRanking = 0, Description = "There are tons of great MVC web frameworks out in the wild, for most major compiled and dynamic languages. They're great tools to get projects prototyped and quickly into production. The Ambition MVC framework is a hobby that turned into a reasonable web framework. Written using Vala, the Ambition framework allows a developer or team of developers to create web applications or RESTful services using a static-typed object oriented language without relying on a VM or a garbage collection cycle. Plus, being compiled, it allows cloud deployment to be easy and inexpensive, as memory and CPU requirements can be a fraction of PHP, Ruby, Python, or Perl sites. While it's not \"officially\" released, it's available on GitHub, and being actively developed. Patches, help, and end users are very welcome, and I'd like to show you more.", AuthorInfo = "Nick Melnick is a Minneapolis-based, multi-language developer, architect, and technology generalist with over fifteen years of experience. He tends to evangelize the underdogs of technology, and is subject to technological whims and experimentation. He is currently a director of development for a local e-commerce company, and occasional contributor to various open source tools.", AuthorTwitter = "@nrmelnick", Room = "Rapson 56", VoteCount = 0 },
                new Talk { Author = "Robert Boedigheimer", Title = "Fiddler and Your Website", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/RobertBoedigheimer.jpg", Stars = 0, TotalRanking = 0, Description = "Fiddler is a great free tool for monitoring HTTP traffic between clients and web servers. It is very helpful for troubleshooting web sites and for gauging performance. Review the basic features and explore advanced techniques for extending Fiddler. Learn how to use Fiddler to capture traffic from smartphones, tablets, and non-Windows platforms.", AuthorInfo = "Robert Boedigheimer works for Schwans Shared Services, LLC providing business solutions with web technologies and leads Robert Boedigheimer Consulting, LLC. Robert has been designing and developing web sites for the past 19 years including the early days of ASP and ASP.NET. He is a Pluralsight Author, an ASP.NET MVP, an author, and a 3rd degree black belt in Tae Kwon Do. Robert has spoken at industry conferences including VSLive, Heartland Developers Conference, DevLink, DevTeach, Tulsa Tech Fest, DevWeek, DevReach, SDC, TechEd, DevConnections, AJAXWorld, and numerous national and international events.", AuthorTwitter = "@boedie", Room = "3-180", VoteCount = 0 },
                new Talk { Author = "Justin Wendlandt", Title = "JavaScript Tips and Tricks to Make Your Life Easier", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JustinWendlandt.jpg", Stars = 0, TotalRanking = 0, Description = "Anyone who has developed for the web has run into JavaScript. It is a language that was first standardized right around the same year I graduated high school (1996). After 10 years of developing applications with C#, I find myself missing certain aspects of the .NET Framework and the C# language that I really wished existed in JavaScript. This talk will go over several aspects of JavaScript from the perspective of a C# guy. We will review tips and tricks to make life easier, software engineering patterns to increase code quality and general guidelines to make JavaScript more maintainable.", AuthorInfo = "Justin Wendlandt is a Senior Consultant at Magenic technologies (www.magenic.com). He is an avid technologist who is passionate about computer science, security, usability and software patterns and practices. Professionally he focuses on using Microsoft technologies to solve business and enterprise problems. You can find out more information about him at http://www.jwendl.net/ or you can follow him on twitter @jwendl.", AuthorTwitter = "@jwendl", Room = "3-210", VoteCount = 0 },
                new Talk { Author = "Erik Onarheim", Title = "HTML5: All Your Games Are Belong to Us", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/ErikOnarheim.jpg", Stars = 0, TotalRanking = 0, Description = "How do you build games in HTML5? In this talk we will learn about the basics of game development and how to apply it in a canvas based HTML5 game. We will be building a simple game live on the screen by leveraging JavaScript and new HTML5 features. We will learn about drawing to the HTML5 canvas, handling key input, maintaining frame rate, the subtleties of performing rotations and translations, setting up audio, sprite animations, basic game physics, and multiplayer support! I will also discuss some lessons in game programming that I learned the hard way so that you don’t have to. If you are interested in web game development, come learn about everything you need to make your first game –from the basics to the advanced.", AuthorInfo = "Erik Onarheim is an Application Developer working for General Mills who loves building cutting edge JavaScript applications. In his spare time he likes to play and develop games, draw comics, study guitar, and drink cheap wine. You can find him on twitter @ErikOnarheim or on his blog, http://erikonarheim.com.", AuthorTwitter = "@ErikOnarheim", Room = "2-260", VoteCount = 0 },
                new Talk { Author = "Todd H. Gardner", Title = "Browser JavaScript Error Tracking", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/ToddHGardner.jpg", Stars = 0, TotalRanking = 0, Description = "The web today is far more than your server stack! Content is combined with a rich interactive layer of JavaScript and mashed up with external social, advertising, or service providers. All this into a rapidly changing environment of new browsers, new rendering engines, new libraries, and new plugins. JavaScript can and should be better--we should know about our errors--and we should fix them! It's our mission to give you the tools to do this. Let's talk about why you should care about your clientside errors, and how to build a basic implementation.", AuthorInfo = "I am a co-founder of {Track:js} and a JavaScript consultant in Minneapolis. I have lead several large single-page application projects, and have been able to distill some general tenants about them and their construction. todd@trackjs.com @toddhgardner.", AuthorTwitter = "@toddhgardner", Room = "3-230", VoteCount = 0 },
                new Talk { Author = "Kevin Whinnery", Title = "JavaScript as a First-Class Citizen on iOS 7", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KevinWhinnery.jpg", Stars = 0, TotalRanking = 0, Description = "One of the most exciting technology improvements announced for iOS 7 was the new JavaScriptCore framework. With this new system framework, developers can write JavaScript code with full access to iOS platform APIs. This means that native UIKit applications, games, and everything in between can now be written in JavaScript, without the addition of a third party framework or missing out on rich platform APIs. After many years in purgatory, JavaScript is now blessed and officially supported by Apple for usage in native iOS apps. In this talk, we'll focus on what developers need to know to take advantage of JavaScriptCore bindings in iOS 7. We will also explore where this new technology fits in alongside existing JavaScript solutions for mobile development, like Appcelerator's Titanium and Apache Cordova (PhoneGap). To demonstrate how this new framework might be used, we will script a simple game using SpriteKit, the new built-in 2D game framework in iOS 7. There are many exciting possible applications of this technology, and I hope the JavaScript community takes full advantage of them.", AuthorInfo = "Kevin Whinnery is a front-end hacker and developer evangelist for Twilio. Kevin has been researching and using JavaScript on mobile for several years, including a four year stint at Appcelerator prior to joining Twilio. Kevin is also the author and maintainer of Twilio's official node.js helper library. Kevin lives in Saint Paul, Minnesota with his beautiful wife and three devious children.", AuthorTwitter = "@kevinwhinnery", Room = "3-230", VoteCount = 0 },
                new Talk { Author = "Wolf Loescher", Title = "How I Learned to Stop Worrying and Love Google Glass: An Introduction", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/WolfLoescher.jpg", Stars = 0, TotalRanking = 0, Description = "Google Glass has acquired mindshare as the first viable mainstream commercial \"wearable computing\" product. But for all the excitement (especially amongst the technorati), there is a lot of fear and doubt. What's it like to wear this thing all day? What can you do with it? What *can't* you do with it? When can I get one? How do I develop for it? Will it make me blind and/or sterile? Join Wolf Loescher to discus the good, the bad, and the the ugly about Google Glass.", AuthorInfo = "Wolf Loescher (@wloescher) is a coder, designer, drummer, singer, and record producer (although not usually all at the same time). He exercises the right side of his brain at DreamPlanGo (dreamplango.com) creating content marketing magic for the web and mobile platforms. Meanwhile, he scratches his musical itches with local celti-cajun folk pop band the Sweet Colleens (sweetcolleens.com).", AuthorTwitter = "@wloescher", Room = "3-230", VoteCount = 0 },
                new Talk { Author = "Kamran Ayub", Title = "Leveling Up Your Windows Phone App", DateTime = new DateTime(2013, 10, 19, 14, 15, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KamranAyub.jpg", Stars = 0, TotalRanking = 0, Description = "In this live coding demo, we’re going to start where most introduction Windows Phone development tutorials leave off, which is: what do you do after you have your basic app working? How do you leverage MVVM, add offline capability, cache data, handle logging & exceptions, and polish it for a great user experience? We’ll take an existing basic application (mine, in fact) and enhance it while I share tips, tricks, and gotchas related to building a fully realized Windows Phone app that will help you level up your existing application and learn what it takes to build a real live app.", AuthorInfo = "Kamran Ayub is a Senior Application Developer working at General Mills who is passionate about technology and sharing his experiences with others. On the side, he works on several personal projects, has contributed to multiple open source libraries, and attempts to balance his development and gaming hobbies, often unsuccessfully. He's frighteningly easy to find, but you can follow him @kamranayub or on his blog, http://kamranicus.com.", AuthorTwitter = "@kamranayub", Room = "Rapson 45", VoteCount = 0 },
                new Talk { Author = "Vince Bullinger", Title = "Cross-Platform Mobile Development", DateTime = new DateTime(2013, 10, 19, 14, 15, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/VinceBullinger.jpg", Stars = 0, TotalRanking = 0, Description = "Mobile development is big and it’s only going to get bigger. You want your app to work on all major mobile platforms, but not everyone has the time, resources or even the desire to learn all of the native mobile frameworks. In this presentation, we’ll learn about how you can make mobile apps that work across all major mobile platforms without learning several entirely new tech stacks by utilizing cross-platform mobile development. We’ll go over some of the most popular cross-platform mobile development frameworks, discuss when to use them vs. native development and when to use each framework.", AuthorInfo = "Vince Bullinger has been a passionate .Net developer and consultant since 2005. He has an MCSD for .NET with C#. In his spare time, he likes to do home projects, work out, play video games and learn everything there is to know about everything.", AuthorTwitter = "@vbullinger", Room = "3-230", VoteCount = 0 },
                new Talk { Author = "Ken Sykora", Title = "Can You Teach me How to Umbraco?", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KenSykora.jpg", Stars = 0, TotalRanking = 0, Description = "Umbraco is free and open source CMS with a great developer community that has been around for a while, but has recently started to really pick up traction. In this presentation, Ken will show you an overview of the features of the CMS, and walk through the basic steps for creating an Umbraco site, covering Document Types, Templates, Macros, and the programmability behind each of these features.", AuthorInfo = "Ken is a .NET developer with intimate knowledge with numerous .NET Content Management Systems, including Ektron, Sitecore, Umbraco, and Sharepoint. As an avid geek and tech hobbyist, he has always been driven to finding awesome ways to integrate music with technology", AuthorTwitter = "@kensykora", Room = "Rapson 56", VoteCount = 0 },
                new Talk { Author = "Ed Jones", Title = "Using Microsoft’s Business Rules Engine with .NET Clients", DateTime = new DateTime(2013, 10, 19, 14, 15, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/EdJones.jpg", Stars = 0, TotalRanking = 0, Description = "One common misconception regarding Microsoft’s Business Rules Engine (BRE) is that you need BizTalk to use it. Actually, you can call the Rules Engine from any .NET code. In this session, we’ll show you how to create a policy in the Business Rules Composer, deploy it to the Rules Engine, and then use Plain Old C# Objects (POCOs) to execute it. We’ll also include a very brief overview of BizTalk 2013 and how the BRE works. The demos will use Visual Studio 2012 and the BizTalk 2013 Business Rules Engine.", AuthorInfo = "Ed Jones is a consultant specializing in Connected Systems and .NET development for RBA. With over 15 years of IT experience, Ed has helped both large and small clients in a variety of industries including banking, healthcare, transportation, manufacturing, and retail. He has served as architect, developer, mentor, and trainer and occasionally throws on the DBA and infrastructure hats as well. You can read about Ed's technical thoughts and experiences as well as pick up a tip or two on his blog, Extremely Talented Monkeys (http://talentedmonkeys.wordpress.com).", AuthorTwitter = "@talentedmonkey", Room = "Rapson 56", VoteCount = 0 },
                new Talk { Author = "Kevin Hakanson", Title = "Internationalize Your JavaScript Application: Prepare for \"the next billion\" Internet Users", DateTime = new DateTime(2013, 10, 19, 14, 15, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KevinHakanson.jpg", Stars = 0, TotalRanking = 0, Description = "Are you prepared for \"the next billion\" internet users, most of whom don't use English as their primary language? This session will explore the globalization (internationalization and localization) of JavaScript based applications. It will look at the ECMAScript Internationalization API and popular open source projects like AngularJS, messageformat.js and jQuery Globalize.", AuthorInfo = "Kevin Hakanson is an application architect for Thomson Reuters where he is focused on highly scalable web applications, especially the JavaScript and security aspects. His background includes both .NET and Java, but he is most nostalgic about Lotus Notes. He has been developing professionally since 1994 and holds a Master’s degree in Software Engineering. When not staring at a computer screen, he is probably staring at another screen, either watching TV or playing video games with his family.", AuthorTwitter = "@hakanson", Room = "3-115", VoteCount = 0 },
                new Talk { Author = "James Greene", Title = "Level-Up Your Web Dev Toolset With GruntJS", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JamesGreene.jpg", Stars = 0, TotalRanking = 0, Description = "Are you writing JavaScript or CSS for a web application? Maybe you even compile some CoffeeScript or SASS? Do you concatenate and minify your files? How about linting them? And you run your unit tests every time you make a change, right? ...RIGHT!? There's always been a lot of grunt work involved with frontend development but there have never been great tools for improving your workflow as a developer. That is, until Node.js came along and completely changed the game in terms of what is possible to do on the server-side. Come see how GruntJS (a VERY useful Node.js module) can make your life easier by taking care of most of that grunt work for you! Adhering to best practices has never been easier. This session will also touch on Node.js, NPM, PhantomJS, Bower, and more.", AuthorInfo = "James Greene is a Lead Software Engineer for Thomson Reuters where he is focused on highly scalable web applications. His recent technical foci include JavaScript (including Node.js, PhantomJS, RequireJS, and more), HTML5, and REST-ful JSON-based services in ASP.NET MVC. He is co-organizer of the Twin Cities JavaScript user group JavaScriptMN. He also moonlights as an official jQuery team member, a core collaborator for the popular JavaScript-related projects PhantomJS, QUnit, and ZeroClipboard, and an open source zealot in general. On the off occasion that he is not staring at a computer or smartphone screen (a rarity indeed), you will find him spending time with his family, playing board games, traveling abroad, hiking, or scuba diving. For more info, check out: http://jamesgreene.net/.", AuthorTwitter = "@_JamesMGreene", Room = "3-125", VoteCount = 0 },
                new Talk { Author = "Lyle Luppes", Title = "FUD in the land of MVC5 and SPAs", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/LyleLuppes.jpg", Stars = 0, TotalRanking = 0, Description = "There is certainly a lot of uncertainty and doubt around the topic of SPAs (Single Page Applications), and that makes any experienced programmer afraid. There are dozens of ways to create SPAs and each one promises to be the best (at least until next month when another new method comes out). Join me as I work through some of the issues faced while creating Single Page Applications using ASP.NET and MVC5. We’ll explore what’s new in Visual Studio 2013, MVC5 and WebAPI, and then look at a couple of techniques for creating SPA applications in MVC using MVC partial pages and using some of the popular libraries like Knockout and Ember. I’m sure we’ll be able to cover all those topics in one hour, right? :)", AuthorInfo = "Lyle Luppes has been developing applications for over 25 years now, starting on mainframes and AS/400’s, then moving to client-server and Windows applications, and then on to web development. After working at very large companies and very small consulting firms, he started his own business in 2000, doing just about everything from building servers to wiring networks to being the Database Administrator. He enjoys doing a wide variety of tasks, but likes pure creative development the best. Lyle has taught a college level class and mentored many developers along the way, and now that his kids are grown and out of the house, he’s looking for new opportunities to share what he has learned. Last year, he wrote the book \"Delivering Mobile-Friendly Websites with MVC4\" (which cracked the top 10 in its category on Amazon briefly), and he is currently working on an MVC5 book.", AuthorTwitter = "@lluppes", Room = "Rapson 56", VoteCount = 0 },
                new Talk { Author = "Joel Kauffman", Title = ".NET API Frameworks", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JoelKauffman.jpg", Stars = 0, TotalRanking = 0, Description = "A look at the various options to build API’s in the .NET world including ASP.NET Web API, Nancy, Simple.Web, ServiceStack and Open Rasta. We’ll look at the benefits and drawbacks of each. There will also be coding examples of how each framework is used to serve data.", AuthorInfo = "Joel Kauffman is the development manager for Vistacomm, a web development company, in Sioux Falls, SD. Joel has spoken previously at various conferences in the region, and enjoys meeting and talking with people who share his passion for technology. When he isn’t speaking or building software, Joel spends time with his wife and 4 kids.", AuthorTwitter = "@ifranto", Room = "3-115", VoteCount = 0 },
                new Talk { Author = "Brian Hogan", Title = "Meet Angular.JS", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/BrianHogan.jpg", Stars = 0, TotalRanking = 0, Description = "Angular.JS from Google introduces a radically different way to build things for the web with HTML and JavaScript. In this talk, we'll take a look at the basic and most useful features of Angular as we build some simple apps and widgets we're already familiar with using new techniques. We'll look at Angular's support for data binding, services, directives, and testing. And we'll also talk about where Angular isn't a good fit.", AuthorInfo = "Brian Hogan is a developer, teacher, and author who loves building things on the web. When not hacking on code, he's making music and playing violent video games, or spending quality time with family.", AuthorTwitter = "@bphogan", Room = "2-260", VoteCount = 0 },
                new Talk { Author = "Erik Rantapaa and Chris Wilson", Title = "The Haskell Ecosystem", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/ErikRantapaa.jpg", Stars = 0, TotalRanking = 0, Description = "This talk will give a tour of the Haskell ecosystem. No knowledge of Haskell is required. The talk will focus on the tools, sites and community resources available for learning and developing in Haskell.", AuthorInfo = "Erik Rantapaa works for Digital River's MyCommerce division and wishes he could use a strongly-typed purely functional language in his day job.", AuthorTwitter = "", Room = "Rapson 45", VoteCount = 0 },
                new Talk { Author = "Brent Edwards", Title = "Cross-platform apps with Windows 8 and Windows Phone 8", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/BrentEdwards.jpg", Stars = 0, TotalRanking = 0, Description = "Windows 8 and Windows Phone 8 now run on the same kernel. What does that mean for you, the developer? Two platforms, one codebase! With a little planning, much of your app code can be re-used between both platforms. In this session, we’ll take a look at useful patterns, tips, and tricks to get you writing one codebase that works across both Windows 8 and Windows Phone 8.", AuthorInfo = "Brent Edwards is an Principal Lead Consultant for Magenic and a co-founder of the Twin Cities Windows 8 User Group. He is an accomplished software developer, architect, mentor, and speaker with over 9 years of experience developing innovative solutions with Microsoft technologies. Brent has worked on projects with ASP.NET MVC and jQuery, WPF, Silverlight, and Windows 8. He is also the author of Charmed (https://github.com/brentedwards/Charmed), an open source, cross-platform MVVM support library for Windows 8 and Windows Phone 8. In addition to working with Microsoft technologies, Brent is also an accomplished Android developer whose apps have more than two million downloads. When not cranking out code, you can find him hanging out with his wife and four kids or riding his wakeboard, snowboard or mountain bike. Check out his blog at http://brentedwards.net/ and follow him on twitter @brentledwards.", AuthorTwitter = "@brentledwards", Room = "Rapson 45", VoteCount = 0 },
                new Talk { Author = "David Washington", Title = "Windows 8.1 Demo", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/DavidWashington.jpg", Stars = 0, TotalRanking = 0, Description = "Microsoft reimagined the PC with Windows 8 and it’s just getting started. Windows 8.1 continues its momentum and brings a new set of innovations to 100 million desktops, laptops and tablets around the world. In this keynote, you’ll see a fresh demo of Windows 8.1 led by an engineer from the Windows User Experience team; from major new improvements, to cool hidden gems and details. Get insight that you only can get from someone from the product team on why decisions were made. Finally, see some cool apps built for Windows 8.1 and get into the code for how they were made.", AuthorInfo = "David Washington is a Microsoft Technical Evangelist based in Minneapolis, MN. As the Microsoft Technical Evangelist, he works with students, startups and independent app developers in the Twin Cities and surrounding area who are interested or need help with Windows 8, Windows Phone and Windows Azure. For the past eight years he worked on User Experience in Windows. Most recently he worked as a Senior Program Manager Lead on Windows 8.1, leading a team of people designing the text suggestions UX and platform for the touch keyboard. Before that, he drove the end-to-end experience for how Windows 8 scales and adapts responsively across all screens sizes, from tablet to laptop to desktop, portrait and landscape and high pixel density screens. He presented some of the developer story at the BUILD 2011 conference and wrote blog the scaling to screens and portrait blog posts on the Building Windows 8 blog. Early on at Microsoft he drove the Windows Explorer, Search and file Dialog features and developer platform. He spoke at the PDC 2008 developer conference about how to integrate into the Windows 7 Explorer features. David has a few apps in the Windows Store that created in his spare time.", AuthorTwitter = "@dwcares", Room = "Rapson 45", VoteCount = 0 },
                new Talk { Author = "Jim Wooley", Title = "Reactive Extensions (Rx) in Action", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JimWooley.jpg", Stars = 0, TotalRanking = 0, Description = "You may have seen the theoretical discussions of Reactive Extensions and heard about the duality of IEnumerable and IObservable, but are still scratching your head to know how and when to use them. In demo filled session, we'll cover a number of cases where it makes sense to consider RX to declaratively compose complex operations over observable sequences in an elegant LINQ like syntax. We may even have some chocolate induced audience participation along the way.", AuthorInfo = "By day, Jim Wooley is a consultant for Slalom Consulting, In his free time, Jim is a frequent speaker, INETA Regional Speaker, MVP, and author of \"LINQ in Action\". He is always striving to stay at the forefront of technology and enjoys the thrill of a new challenge. He has been active evangelizing LINQ since it's announcement in 2005. In addition, he attempts to pass on the insights he has gained by being active in the community, including organizing and speaking at code camps and regional events, including DevLink, DevWeek, CodeMash, CodeStock, VS Live, and MIX.", AuthorTwitter = "@jimwooley", Room = "Rapson 56", VoteCount = 0 },
                new Talk { Author = "Adam Barney", Title = "Learn the Basics: Inversion of Control", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/AdamBarney.jpg", Stars = 0, TotalRanking = 0, Description = "What is IOC? You’ve no doubt heard the term thrown around by seasoned developers. They sing of its usefulness and power – but when you try to learn it, it all seems to go over your head. That was me a few years ago. I finally made a concerted effort to really learn IOC and see what all these smart people were raving about. In this session, I will share my knowledge of IOC and try to help you understand why Inversion of Control is as good as the alpha geeks say it is.", AuthorInfo = "Adam is a Microsoft C# MVP and co-leader of the Lincoln .NET Users Group and Nebraska Code Camp. Having a deep passion for solving problems, he has turned to writing code as an outlet for that passion. Starting in the 4th grade on a Commodore64, he has continually pushed himself to learn more about the construction of software – and he loves sharing that knowledge and passion with others. It’s a fantastic time to be a developer – and Adam is loving every minute of it. When not speaking at conferences, or hanging out with his wife and 2 kids, he runs his own independent consulting company – Barney Consulting (www.barneyconsulting.net).", AuthorTwitter = "@cabarney", Room = "3-115", VoteCount = 0 },
                new Talk { Author = "Brette Esterbrooks", Title = "Securing The ASP.NET Web API", DateTime = new DateTime(2013, 10, 19, 14, 15, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/BretteEsterbrooks.jpg", Stars = 0, TotalRanking = 0, Description = "With OpenID, OAuth, Security Token Services, Basic Authentication, Digest Authentication and many other approach's the security story for the ASP.Net Web API is a confusing one to say the least. In this session we will talk about the various approaches to securing your Web API's as well as choosing the right method for your situation. In doing so we will cover authentication and authorization, cryptography and the various extension points of the ASP.NET Web API Framework that can help us create a production grade service.", AuthorInfo = "Brette Esterbrooks is a software developer with 10 years of experience in both Web Application and Rich Client development. As an independent contractor in the Twins Cities area Brette has worked with many large and medium sized companies as well as several non-profit organizations. Most recently his work has been focused on WPF and MVC application development. His other interests include Cloud Computing, Software Usability, and exploring various Frameworks. Brette is a large proponent of the ‘Keep It Simple Stupid’ principle and believes strongly that frameworks should be developed overtime organically to continually reduce the friction they create. When not working Brette enjoys the study of economics, spending time on his Motorcycle, walking his dogs, and traveling with his wife.", AuthorTwitter = "", Room = "3-210", VoteCount = 0 },
                new Talk { Author = "Kurt Wiersma", Title = "Building a Real World Single Page App with AngularJS", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KurtWiersma.jpg", Stars = 0, TotalRanking = 0, Description = "Come learn how a highly interactive, single page app, was built with AngularJS and Bootstrap. AngularJS is a full stack MVC Javascript framework. It has features for routing, client side templates, REST, two-way data binding, and UI components, built into one integrated package. In this presentation you will: Learn what AngularJS is and how you can use it in an app. Learn how AngularJS works with servers by using a REST based API. See some tips and tricks for building single page applications with Javascript. Learn about the tooling available to help you build these types of Javascript apps.", AuthorInfo = "Kurt Wiersma is a web developer with over 12 years of experience. He has worked with Java, CFML, Grails, Python, and C# over the course of his career. Currently he works for the American Academy of Neurology leading a team of developers building MVC apps with C#.", AuthorTwitter = "@kwiersma", Room = "3-180", VoteCount = 0 },
                new Talk { Author = "Stephen Erstad", Title = "File System API: File I/O for Websites", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/StephenErstad.jpg", Stars = 0, TotalRanking = 0, Description = "HTML5 has brought us many new ways to deliver rich content to the web. The File System API is one way we can enable offline applications that deal with actual files in a sand boxed environment for a site. It allows us to store binary files such as documents, images, and even JSON. The files can then be referenced with file system URIs to deliver them to the user, build the site itself, or even serve data using XHR. Learn the basics of the API, dealing with browser compatibility or lack there of, common use cases, and see tools to help you build your app in this code-centric presentation.  Here is the tests and app I will be reviewing to cover the API:  StephenErstad/FileSystemApiDemo.  It can be run as a Node or .NET web app.", AuthorInfo = "I am a 2009 graduate from the University of Minnesota CSE. I work for General Mills as a software developer focused on building hybrid mobile applications. Recently I have been focusing on building an enterprise offline web application that utilizes many pieces of HTML5 such as the application cache (with a dynamically generated manifest), DOM local storage, and file system API to deliver content to our customers on multiple platforms.  Outside of coming up with reasons not to build native clients, I am into literature, video games, philosophy, and anime.", AuthorTwitter = "@StephenErstad", Room = "3-115", VoteCount = 0 },
                new Talk { Author = "Mike Weber", Title = "Breaking out of the MVC", Description = "Ruby on Rails, and other Model/View/Controller based frameworks, are great tools for quickly creating web applications. Unfortunately the MVC is not a one-size-fits-all pattern and it tends to point developers away from proper object-oriented design. We'll talk about how to organize code beyond the MVC, decoupling application logic from the MVC, and when it's best to use a Service Layer instead of Models. While the talk will mostly focus on Rails, we'll be discussing established object-oriented programming principles and these ideas should be applicable to anyone working with an MVC-based framework.", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/MikeWeber.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "We got nuttin' on this guy.", AuthorTwitter = "", Room = "3-125", VoteCount = 0 },
                new Talk { Author = "Md Khan", Title = "High Performance JavaScript and CSS", Description = "The entire web is married to JavaScript. That’s not the fact. Fact is the guys who are cooking for the web, is crazy about JavaScript. Hence, you cannot imagine a single website (desktop or mobile) without JavaScript. Saving the marriage is not an option when your world is occupied by your better half in loading resources, delicious libraries, fancy charts/ visualization, two way binding, interactions with DOM, responsive U,I so and so on... When JavaScript do the core work like (grocery, taking dogs to walk/ kids to child care, weekends/ vacation plan, marathon shopping) CSS makes your site interesting. CSS performance is the silent killer that we always ignore. The goal of this talk is not to save the marriage rather to make the marriage most enjoyable, highly interesting and tremendously performing. High performance doesn’t have to some miracle that somehow works. After this talk, you would be the guy who rocks for high performance JavaScript and CSS. And you will believe, high performance code could reusable, readable and maintainable.", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/MdKhan.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "As a web developer focusing on the front end, Md Khan is addicted to JavaScript. MD spends most of his time to write “hello world” when someone tweets a new JavaScript library. But he doesn’t stop there rather kills his weekends to convert “hello world ” to glorious “Todo app” so that he can update his linkedin profile with new frameworks and libraries. If you are still interested to read a job title (you might be an auto insurance agent), MD is a senior web developer at Nielsen, Chicago, IL.", AuthorTwitter = "@mdkhan005", Room = "3-210", VoteCount = 0 },
                new Talk { Author = "Peter J. Farrell", Title = "Intro to Django", Description = "Django is a Python MVC web framework for perfectionists with deadlines. In this presentation, we'll explore how Django exploits the principle of DRY and the ecosystem that surrounds Python by building a simple polling application for voting on issues. Django powers many well-know websites such as Instagram, Pinterest, PBS and Mozilla. Don't worry if you've never used Python before... you'll be surprised how productive you can be in Python with little knowledge.", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/PeterJFarrell.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Hailing from the frigid tundra of Minnesota, Peter J. Farrell has a Bachelor of Music degree from the Johns Hopkins University in Baltimore, Maryland. While studying music, Peter took his life-long interest with computers and started to learn about programming. He has been working with various technologies since 2001 and currently specializes in web development with Python and Django. \r\n\r\nHe currently is a Principal Technologist for GreatBizTools, a firm that offers online skill and personality testing for employers. Peter lives in Minneapolis with his wife, Ally and their two dogs.", AuthorTwitter = "@maestrofjp", Room = "3-125", VoteCount = 0 },
                new Talk { Author = "Keith Dahlby", Title = "Git More Done", Description = "You've seen the intro, you've cloned from GitHub, but you're still not convinced Git's learning curve is worth the climb. This session aims to shed some light from the real world on how Git is different, why the differences matter, and introduce some features and use cases you never knew you couldn't live without. Topics covered will include interactive rebase, interactive add, reflog, bisect and more. Let's discuss how these things happen, why it's a blight on our profession, and how we might improve the situation. I don't have all the answers, but I do have stories...and I'm sure you do too.", DateTime = new DateTime(2013, 10, 19, 15, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/KeithDahlby.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Keith Dahlby is a new father, web developer, Git enthusiast, language geek and three-time C# MVP from Cedar Rapids, IA. By day he sells motorcycle parts at J&P Cycles; by night he sometimes blogs with Los Techies. His open source efforts include posh-git, a Git environment for PowerShell; and FSRazor, F# support for the Razor view engine. Keith has spoken at community events around the Midwest and studied Human-Computer Interaction at Iowa State University. His talks have been described as “terrific!”, “very interactive!”, and “the best I’ve seen all hour!”.", AuthorTwitter = "@dahlbyk", Room = "3-125", VoteCount = 0 },
                new Talk { Author = "Jenna Pederson", Title = "Developing Productivity", Description = "Learn real world techniques for improving your productivity as a developer. We'll skip past the hype that it's impossible to measure an individual developer or a team's productivity and jump right into the meat of learning how to tweak your personal and team development processes to deliver more value to your clients. This session will take a look at practices to help you improve, processes, and tools - everything from automating your app deployment to using a clipboard manager. As one of the best ways of finding new productivity tweaks is working with other developers, we'll also gather suggestions from the audience on what works in the wild.", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JennaPederson.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Jenna Pederson is an independent software developer. She has worn a variety of hats in the development of building desktop software, web, and mobile applications. With experience from the front-end all the way down to the physical servers, from development to business analysis and testing, Jenna is a passionate developer who enjoys getting other engineers excited about the technology and how to solve business problems.", AuthorTwitter = "@jennapederson", Room = "3-115", VoteCount = 0 },
                new Talk { Author = "Judah Gabriel Himango", Title = "Lambdas for Llamas: TypeScript from Zero to Web App", Description = "JavaScript for big apps on the web has never been a great proposition. Enter TypeScript: application-scale JavaScript development. Use TypeScript to whip your web app's complexity into shape using types, modules, classes, and more. In this talk, we'll build a web app from scratch using TypeScript to see what this language is all about. Fun with lambdas and llamas.", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JudahHimango.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Hi, I'm Judah. I'm a technologist and builder of things. I've been blogging for a decade and coding since my teens. I love technology! I run a startup around internet radio, I work for Avtex by day and @ayende by night. Outside of work, I play music, help run a Messianic Jewish congregation, play sports, and enjoy life with my wife and 2 kids. My talks? Live coding, zero bullet points, keeping the fun in coding. Enjoy!", AuthorTwitter = "@judahgabriel", Room = "Rapson 45", VoteCount = 0 },
                new Talk { Author = "Mike R. Emo", Title = "Single Page Application with Knockout, Breeze, & WebAPI", Description = "Single Page Application (SPA) with WebAPI, Knockout, and Breeze. Many of us have been using AJax for a long time to make our web applications modern and responsive. In this presentation I will demonstrate how to develop your entire UI with client side javascript, css, and html, using WebAPI for back end database interaction and middle tier logic. This presentation uses a combination of javascript libraries, including JQuery, Knockout, BreezeJS, History.JS, and Q-Js. These libraries make writing SPA applications easier than ever, with client side data binding and observable javascript objects among other features.", DateTime = new DateTime(2013, 10, 19, 12, 45, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/MikeREmo.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Mike R. Emo is the founder of iEmoSoft consulting and is a senior software engineer and architect with over 15 years of experience specializing in web application, fat client, database design / implementation, and distributed systems development. Mike recently worked with Sorin Medical Group to develope their version 1.0 remote monitoring system, allowing cardiac physicians to remotely monitor their patients. As an independent consultant, he enjoys the opportunity to connect with a wide range of personalities and cultures as well as emerging technologies. Most recently Mike worked with Make Music in Eden Prairie to help them with their rebranding and ecommerce initiatives.", AuthorTwitter = "", Room = "3-125", VoteCount = 0 },
                new Talk { Author = "Brandon H.", Title = "T4 - Let Your Code Write Your Code!", Description = "As Software Engineers, doing the same thing twice immediately causes alarms to go off in our brains. So what if you could actually write code that would… write code for you? Come check out what .Net’s Text Template Transformation Toolkit (aka T4) has to offer!", DateTime = new DateTime(2013, 10, 19, 9, 0, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/BrandonH.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "I am a Sr. Software Engineer for the nation’s largest hearing aid manufacturer located here in the twin cities. I have worked in this job for 6 years, while also working on Windows Phone and Windows 8 applications as a hobby. I also worked for a mobile startup developing a cross-platform framework.", AuthorTwitter = "", Room = "3-180", VoteCount = 0 },
                new Talk { Author = "Jason Hsu", Title = "Creating Ruby Gems: Why and How", Description = "You've learned the basics of Ruby. Now it's time for you to earn your 15 minutes of fame by publishing well-tested Ruby gems. Why should you publish a gem? Why should your gem include formal tests? How do you write, test, and publish your gem?", DateTime = new DateTime(2013, 10, 19, 14, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/JasonHsu.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Jason Hsu is the founder and lead developer of two Rails sites, Doppler Value Investing (http://www.dopplervalueinvesting.com) and Bargain Stock Funds (http://www.bargainstockfunds.com). He has published the dvi_scrape and bsf_scrape gems that acquire and process the financial data needed for these sites. Although his formal background is in electrical engineering, he is currently seeking a position as a Ruby on Rails developer.", AuthorTwitter = "", Room = "3-180", VoteCount = 0 },
                new Talk { Author = "Allen Sanborn", Title = "Automate the Things You Hate", Description = "Spend more time coding and less time dealing with environments, builds, configuration, creating documentation, testing and talking to people you don't like by creating tools that support the development process and help you leave at 5PM. We spend all day creating tools that help the business be more efficient so why don't we create tools that allow us to be more efficient? Come and learn a bit about how to automate the configuration of environments (DEV to PROD), wrangle your builds/deployments and automate ALL THE THINGS from a .Net/Windows perspective. Tools = { .Net, PowerShell, Psake, Nuget, Chocolatey, Boxstarter, TFS 2013 Build-Deploy-Test, TFS Deployer, Virtual Machines }", DateTime = new DateTime(2013, 10, 19, 10, 30, 0), PhotoUrl = "http://bitshuvacdn.com/speakr/AllenSanborn.jpg", Stars = 0, TotalRanking = 0, AuthorInfo = "Allen is a developer from Duluth, Minnesota. He's a writer of code. Rider of bicycle. Player of games.", AuthorTwitter = "@1001monkeys", Room = "3-230", VoteCount = 0 }
            };

            using (var session = RavenInstance.Db.OpenSession())
            {
                allTalks.ForEach(session.Store);
                session.SaveChanges();
            }
        }
    }
}
